// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjsbEA3w4kmTscFRhQb3zPftf50tlPcr8',
    appId: '1:553170305347:web:190cc05d888b00d7112ff6',
    messagingSenderId: '553170305347',
    projectId: 'drugcart-4be9a',
    authDomain: 'drugcart-4be9a.firebaseapp.com',
    databaseURL: 'https://drugcart-4be9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drugcart-4be9a.appspot.com',
    measurementId: 'G-GDRZEZNBN4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAI5hSm4Aj4UsBRb3IZT3MfGb6SntARQzY',
    appId: '1:553170305347:android:26f225c1bc49ac55112ff6',
    messagingSenderId: '553170305347',
    projectId: 'drugcart-4be9a',
    databaseURL: 'https://drugcart-4be9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drugcart-4be9a.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB-zV26qyxI54p6TCm2uyJHmArf7zZSEwc',
    appId: '1:553170305347:ios:0f3169efca5e5c3c112ff6',
    messagingSenderId: '553170305347',
    projectId: 'drugcart-4be9a',
    databaseURL: 'https://drugcart-4be9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drugcart-4be9a.appspot.com',
    iosBundleId: 'com.example.drugcart',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB-zV26qyxI54p6TCm2uyJHmArf7zZSEwc',
    appId: '1:553170305347:ios:0f3169efca5e5c3c112ff6',
    messagingSenderId: '553170305347',
    projectId: 'drugcart-4be9a',
    databaseURL: 'https://drugcart-4be9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drugcart-4be9a.appspot.com',
    iosBundleId: 'com.example.drugcart',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjsbEA3w4kmTscFRhQb3zPftf50tlPcr8',
    appId: '1:553170305347:web:4b5225253434f17d112ff6',
    messagingSenderId: '553170305347',
    projectId: 'drugcart-4be9a',
    authDomain: 'drugcart-4be9a.firebaseapp.com',
    databaseURL: 'https://drugcart-4be9a-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'drugcart-4be9a.appspot.com',
    measurementId: 'G-XLGBZW0JPQ',
  );
}
