import 'package:drugcart/user/model/widget/customtext.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class LegalInformation extends StatefulWidget {
  const LegalInformation({super.key});

  @override
  State<LegalInformation> createState() => _LegalInformationState();
}

class _LegalInformationState extends State<LegalInformation> {
  @override
  Widget build(BuildContext context) {
    return  Scaffold(
      appBar: AppBar(
        title: CustomText(text: 'Legal Information', size: 20,weight: FontWeight.bold,),centerTitle: true,
      ),
      body: Padding(
        padding: const EdgeInsets.all(18.0),
        child: Column(
          crossAxisAlignment: CrossAxisAlignment.start,
          children: [
            CustomText(text: 'Terms & Conditions', size: 20,weight: FontWeight.w600,),
            Padding(
              padding: const EdgeInsets.only(top: 20),
              child: CustomText(text: 'his document (“Terms”) is an electronic record in terms of Information TechnologyAct, 2000 and rules thereunder, as applicable and the amended provisionspertaining to electronic records in variousstatutes, as amended from time to time by the Information Technology Act, 2000. This electronic record is generated by a computersystem and does not require any physical or digital signatures.   This document is published in accordance with the provisions of Rule 3(1) of the Information Technology (Intermediaries Guidelines and Digital Media Ethics Code) Rules, 2021 that requires publishing of the rules and regulations, privacy policy and Terms for access or usage of www.Drugcart.in website and its mobile applications.',
               size: 16,color: Colors.grey,),
            )
          ],
        ),
      ),
    );
  }
}